language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_script:
    # Travis versions of these are really outdated
    - pip install -U mock nose pytest
    # Only used in production for python3.4- but required for tests
    - pip install cryptograpy
script:
    - python setup.py validate
