language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_script:
    # Travis versions of these are really outdated
    - pip install -U mock nose pytest
    # Install wheel with pip instead of building from source
    - pip install  cryptography
script:
    - python setup.py validate
