language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_script:
    # Travis versions of these are really outdated
    - pip install -U mock nose pytest
    # Install wheel with pip instead of building from source but only for
    # Python 2 and 3.3
    - if [[ $TRAVIS_PYTHON_VERSION == 2* || $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install cryptography; fi
script:
    - python setup.py validate
