language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_script:
    # Travis versions of these are really outdated
    - pip install -U mock nose pytest
    # Only used in production for python3.4- but required for tests
    - pip install cryptography
    # Enable sending Coverage data
    - pip install codecov
script:
    - python setup.py validate
after_success:
    - codecov
