language: python
python:
  - "3.5"
  - "3.6"
before_script:
    # Travis versions of these are really outdated
    - pip install -U mock nose pytest
    # Enable sending Coverage data
    - pip install codecov
script:
    - python setup.py validate
after_success:
    - codecov
